---
apiVersion: v1
kind: Secret
metadata:
  name: develocity-test-distribution-registration-key-secret
  namespace: default
stringData:
  tdRegistrationKey: <<registration-key>>
  tcCloudToken: <<testcontainers-cloud-token>>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: develocity-test-distribution-agent
  labels:
    app.kubernetes.io/instance: test-distribution-agent-<<pool-id>>
    app.kubernetes.io/part-of: gradle-enterprise
    app.kubernetes.io/component: test-distribution-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-distribution-agent-<<pool-id>>
      app.kubernetes.io/part-of: gradle-enterprise
      app.kubernetes.io/component: test-distribution-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test-distribution-agent-<<pool-id>>
        app.kubernetes.io/part-of: gradle-enterprise
        app.kubernetes.io/component: test-distribution-agent
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 0
        fsGroup: 0
      terminationGracePeriodSeconds: 600
      containers:
        - name: develocity-test-distribution-testcontainers-cloud-agent
          image: <<your-td-tcc-image>>
          resources:
            requests:
              memory: 1Gi
              cpu: 2
            limits:
              memory: 4Gi
              cpu: 2
          env:
            - name: TEST_DISTRIBUTION_AGENT_SERVER
              value: https://<<develocity-hostname>>
            - name: TEST_DISTRIBUTION_AGENT_REGISTRATION_KEY
              valueFrom:
                secretKeyRef:
                  name: develocity-test-distribution-registration-key-secret
                  key: tdRegistrationKey
            - name: TEST_DISTRIBUTION_AGENT_POOL
              value: <<pool-id>>
            - name: TC_CLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: develocity-test-distribution-registration-key-secret
                  key: tcCloudToken
            - name: TEST_DISTRIBUTION_AGENT_CAPABILITIES
              value: <<optional-capabilities, tcc for example>>
